### ISSUE TITLE
Importing react-native-openpgp crashes react-native app. Fails silently.

### ISSUE THREAD

**Issue by jonlaing** [orhan/react-native-openpgp#1]
I'm pretty sure I'm using this properly. When I import `react-native-openpgp` into my project, my app crashes, and there's no error message. This happens whether I import it via ES6 modules, or CommonJS.

```
'use strict';

import React, {
  AsyncStorage
} from 'react-native';

import pgp from 'react-native-openpgp';
```

Yeah, just crashes there. No warnings, no errors, nothing...

**Versions:**
- ReactNative 0.24.1
- Xcode 7.3
- NPM 3.3.6
- Node 5.0.0

**Comment by orhan** [comment]
That's strange, no errors?
I have it working on project that had already been set up.

Let me check this later today, I'll create a sample project and make sure that I've not forgot anything! :)

**Comment by orhan** [comment]
@jonlaing Sorry, I haven't had time yet to check out the errors. But I had problems with this repo too after updating my RN build. Those should be fixed now.

Can you try it out again?

Also one thing I missed to mention in the install instructions:
This library relies on the RNRandomBytes (https://www.npmjs.com/package/react-native-randombytes) library, can you check whether you have setup that correctly? :)
