### ISSUE TITLE
react-native-openpgp error

### ISSUE THREAD

**Issue by athirajyothi22** [orhan/react-native-openpgp#12]
node_modules\react-native-openpgp\src\crypto\public_key\jsbn.js: Identifier 'nbits' has already been declared
![image](https://user-images.githubusercontent.com/74182706/104643171-0318a600-56d2-11eb-9987-be4b1954413c.png)

I am getting an error like this while installing and running react-native-OpenPGP. Can anyone help, please?

**Comment by orhan** [comment]
Fixed with #13
