### ISSUE TITLE
Fails on crypto/random.js

### ISSUE THREAD

**Issue by sarriaroman** [orhan/react-native-openpgp#2]
When I try to encrypt always fails on random.js because isaacson is undefined.

```
for (var i = 0; i < buf.length; i++) {
   buf[i] = Math.floor((isaacson.random() * 255));
}
```

**Comment by orhan** [comment]
@sarriaroman I just realized that I forgot to mention that this library has a dependency on the React-Native-Random-Bytes. Please make sure to install and setup that first and check again? :)

Link is in the updated README.md.

**Comment by sarriaroman** [comment]
Yes, I saw the previous issue but doesn't solve the issue. For some reason `generateRandomValues` is never being called, so, isaacson is undefined. I made a quick fix in the next method and is working but I'm completely sure about it

```
getRandomValues: function(buf) {
    if (!(buf instanceof Uint8Array)) {
      throw new Error('Invalid type: buf not an Uint8Array');
    }
    if (typeof window !== 'undefined' && window.crypto && window.crypto.getRandomValues) {
      window.crypto.getRandomValues(buf);
    } else if (typeof window !== 'undefined' && typeof window.msCrypto === 'object' && typeof window.msCrypto.getRandomValues === 'function') {
      window.msCrypto.getRandomValues(buf);
    } else if (nodeCrypto) {
      var bytes = nodeCrypto.randomBytes(buf.length);
      buf.set(bytes);
    } else if (this.randomBuffer.buffer) {
      this.randomBuffer.get(buf);
    } else {
        if(!isaacson) {
            isaacson = new Isaac.Isaac();
        }

      for (var i = 0; i < buf.length; i++) {
        buf[i] = Math.floor((isaacson.random() * 255));
      }
    }
  },
```

**Comment by orhan** [comment]
Oh!
I recently updated the mechanism around the randomization algorithm because it was not secure enough and forgot to update the README.md, sorry my bad! :/

Please read the "Before Usage" section and try again, should work now! :)

The way you are using it, it may not crash anymore, but it is not safe to use in a strict production environment, because the Issac randomizer does not get a proper seed.

**Comment by sarriaroman** [comment]
Thanks for your help... I will take a look and I will let you know if works :)

I know is not safe haha.

**Comment by sarriaroman** [comment]
I tried several times but is always ending in the catch of the method `generateRandomValues` from random.js.

**Comment by orhan** [comment]
Can I see post your code on how you and what method you are calling?

**Comment by sarriaroman** [comment]
This is the code snippet

```
encrypt(data) {
        return new Promise((resolve, reject) => {
            openpgp.prepareRandomValues().then(() => {
                    var params = {
                        data: JSON.stringify(data),
                        publicKeys: this._public_key
                    };

                    openpgp.encrypt(params).then((res) => {
                        resolve(res.data);
                    }).catch(reject);
                }).catch((err) => {
                    reject(err);
                });
        });
    }
```

**Comment by orhan** [comment]
I have restructured the whole library now, so it doesn't rely on external libraries and also doesn't need the `prepareRandomValues` anymore. :)

Please uninstall the library and follow the instructions, this really should work now. :D

**Comment by sarriaroman** [comment]
AWESOME! Thanks! I will try with the new one!

**Comment by sarriaroman** [comment]
Worked like a charm! Fantastic job and thanks! I'll close the issue now.

**Comment by orhan** [comment]
Awesome, happy coding! 👍
